all:
	gcc -g  -std=gnu99 -D_GNU_SOURCE -DBUCKETSET_TEST -DDEBUG_LOG -O0 slice.h slice.c utils.h utils.c \
		log.h log.c vector.h vector.c \
		hash.h hash.c list.h list.c bucket_store.h bucket_store.c  \
		bucket_object.h   bucket_object.c bucket.h bucket.c bucketset.h bucketset.c \
		-o test
