all:
	gcc -g -DBUCKETSET_TEST -DDEBUG_LOG -O0 slice.h slice.c utils.h utils.c \
		log.h log.c vector.h vector.c \
		hash.h hash.c list.h list.c bucket_store.h bucket_store.c  \
		bucket_object.h  bucket_item.h bucket_item.c \
		bucket_object.c bucket.h bucket.c bucketset.h bucketset.c \
		-o test



